addSbtPlugin("com.eed3si9n"      % "sbt-unidoc"      % "0.4.2")
addSbtPlugin("com.47deg"         % "sbt-microsites"  % "1.2.1")
addSbtPlugin("org.scalameta"     % "sbt-mdoc"        % "2.2.17")
addSbtPlugin("com.github.gseitz" % "sbt-release"     % "1.0.11")
addSbtPlugin("com.jsuereth"      % "sbt-pgp"         % "2.0.0")
addSbtPlugin("org.xerial.sbt"    % "sbt-sonatype"    % "3.7")
addSbtPlugin("com.typesafe.sbt"  % "sbt-ghpages"     % "0.6.3")
addSbtPlugin("org.scala-js"      % "sbt-scalajs"     % "1.4.0")
addSbtPlugin("com.typesafe"      % "sbt-mima-plugin" % "0.6.1")
addSbtPlugin("org.scoverage"     % "sbt-scoverage"   % "1.6.0")
addSbtPlugin("pl.project13.scala" % "sbt-jmh"        % "0.3.6")

addSbtPlugin("org.portable-scala" % "sbt-scalajs-crossproject" % "1.0.0")
addSbtPlugin("org.portable-scala" % "sbt-scala-native-crossproject" % "1.0.0")
addSbtPlugin("com.codecommit"     % "sbt-github-actions"       % "0.10.1")
addSbtPlugin("ch.epfl.lamp"       % "sbt-dotty"                % "0.5.1")
addSbtPlugin("org.scala-native"   % "sbt-scala-native"         % "0.4.0")

